---
dependencies:
  - git
  - unzip
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python-pip
  
apt_key: https://apt.dockerproject.org/gpg
apt_repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
compose_url: https://github.com/docker/compose/releases/download/1.11.1/docker-compose-Linux-x86_64
compose_path: /usr/local/bin/docker-compose